### ISSUE TITLE
Adjust PWA to support review images

### ISSUE THREAD

**Issue by stormofice** [mensatt/frontend-old#102]
The PWA config still seems to rely on the non backend url.
https://github.com/mensatt/frontend/blob/1ed0682580b2309c733a761f65b5a2ed3cdc4ef7/next.config.js#L18-L21

Do we even have proper PWA support currently or should we disable them until we get to fully implement them?

**Comment by GamerBene19** [comment]
Yes we do have proper PWA-Support. The config you are referring to actually is the nextjs-config (which does affect not only PWA but the whole app). The change that you want is mandatory for using images supplied by the backend and already implemented in https://github.com/mensatt/frontend/commit/31b286efcebe7db01a8b01e5ee4f71de933885a4

I think this issue can be closed?

**Comment by stormofice** [comment]
Seems good, didn't see the commit. Closed.
