### ISSUE TITLE
Missing/wrong styling for some components

### ISSUE THREAD

**Issue by StealWonders** [mensatt/frontend-old#128]
- [x] API selector 
![image](https://user-images.githubusercontent.com/6114858/182045494-11571086-b505-4fda-b91e-683e1b40e42c.png)

- [x] Missing social icons like in draft (GitHub, Discord, Email)
![image](https://user-images.githubusercontent.com/6114858/182045517-377b98d5-9e2d-4402-9c3a-849e1750dfca.png)

- [x] Add some padding between copyright and footer navigation
![image](https://user-images.githubusercontent.com/6114858/182045553-7a366599-8126-44ef-8143-1dcef01346c4.png)

- [x] Change "Mehr anzeigen" in the tag section to "..." or use the icon below
![image](https://user-images.githubusercontent.com/6114858/182045580-07f9d79c-474f-4cc9-8acb-63caea94b70e.png)
![image](https://user-images.githubusercontent.com/6114858/182045577-57f60aa9-06f9-46b8-bf86-ea2642af886e.png)
![image](https://user-images.githubusercontent.com/6114858/195874218-55e33903-6416-41fd-954a-bf803fdde3b7.png)

- [x] Move/align the Mensatt logo a bit the the right (mobile)
- [x] Center the Navigation icon vertically (mobile)
![image](https://user-images.githubusercontent.com/6114858/182045613-01aa7e64-1288-48f4-8523-1b0767cce28d.png)

**Comment by GamerBene19** [comment]
You also can't scroll in the rating dialogue.

**Comment by maanex** [comment]
See #146
