### ISSUE TITLE
Show Calories per Euro

### ISSUE THREAD

**Issue by jzbor** [mensatt/frontend-old#134]
Hello,
One of the most important metrics is performance per value or regarding food calories per euro. Please expose this very important measurement via your UI. A little bird told me that calories and price are already exposed via the API...

Regards

**Comment by GamerBene19** [comment]
Great idea @jzbor! Currently my capacities are very limited because of exams, but I'll take a look at this feature once said exams are over!

Rock on! :metal:

**Comment by jzbor** [comment]
Bump

**Comment by jzbor** [comment]
Hello,
First of all thanks for keeping up the great work.
It is truely astonishing to see such an impressive platform being completed in such a short span of time.
However no service is visible to customers without good Search Engine Optimization.
Me and my team have plentiful experience with multiple satisfied customers.
Please reach out to us at jeff@not-a-shady-business.org.

PS: Plis fix calories per euro it is very wichtig

**Comment by jzbor** [comment]
@maanex

**Comment by herkulessi** [comment]
![image](https://github.com/mensatt/frontend/assets/31536990/f37ab550-ce67-436d-a55d-5fb150758e8b)

**Comment by maanex** [comment]
Dear [Name],

Thank you for reaching out. I wanted to inform you that you have contacted me outside of my regular business hours. However, I appreciate your message and I assure you that I will respond to your inquiry as soon as I am available. Please expect a prompt reply when I return to work.

Thank you for your understanding.

Best regards,
[Your Name]

**Comment by maanex** [comment]
Dear valued user,

We are excited to announce a brand new feature that has been added to our popular food website Mensatt based on your valuable feedback and suggestions. We have been working diligently behind the scenes to bring you an enhanced experience, and we are thrilled to introduce the option to show calories per euro in our extensive menu listings!

We understand the importance of making informed choices when it comes to your dietary needs and budget. With this new feature, you can now effortlessly assess the caloric value of the meals and dishes available on Mensatt in relation to the price you pay. This innovative addition aims to empower you to make more conscious decisions about your food selection, providing you with valuable insights into the nutritional value you receive for every euro you spend.

To access this exciting feature, we kindly request you to reload your Mensatt app or website. This will enable the necessary updates to take effect and ensure that the newly added option becomes visible to you. Once you've reloaded the app, you will notice the "Calories per Euro" toggle or filter prominently displayed in the menu section. By activating this option, you can instantly see the caloric value of each food item relative to its cost, allowing for a more comprehensive evaluation of your meal options.

We truly hope that you find this new addition to Mensatt helpful and enjoyable. We deeply value your feedback and strive to create a user-centric platform that caters to your specific needs and desires. This feature has been implemented with your well-being and satisfaction in mind, and we sincerely believe it will assist you in making more informed choices about your meals, ensuring a harmonious balance between nutrition and affordability.

We encourage you to explore this feature and embrace the benefits it offers. Your engagement and support inspire us to continually improve and refine our services, and we are grateful for your continued trust in "mensatt." Should you encounter any issues or have further suggestions, our dedicated support team is always available to assist you.

Thank you once again for being an integral part of our community. We are confident that the addition of the "Calories per Euro" option will elevate your food selection experience on Mensatt and contribute to your overall satisfaction.

Best regards,
The Mensatt Team
