### ISSUE TITLE
Stars don't correspond to numeric rating

### ISSUE THREAD

**Issue by uzantome** [mensatt/frontend-old#135]
![Screenshot_20221011-153758.png](https://user-images.githubusercontent.com/20319107/195107621-37fb5b04-b4c8-45ba-a6a0-e8b8638c84e7.png)

**Comment by GamerBene19** [comment]
Is intended behavior, the number in braces is the amount of reviews, not the average value. We should probably add a hover-text :thinking:

**Comment by StealWonders** [comment]
Unsure if it would be smarter or perhaps more intuitive to display the avg rating in the brackets. Perhaps another option would be to remove the brackets altogether and only display additional information on hover.

**Comment by stormofice** [comment]
I would display the average rating there and move the overall rating count to the "show more" view.
You should be able to estimate the amount of reviews by the average rating anyway.

**Comment by StealWonders** [comment]
Another example of how we could solve the issue: 
![image](https://user-images.githubusercontent.com/6114858/197866055-e27f4025-a06c-437e-93dd-bded063b3d99.png)

**Comment by maanex** [comment]
> I would display the average rating there and move the overall rating count to the "show more" view.
> You should be able to estimate the amount of reviews by the average rating anyway.

This is not in line with established rating uis


> Another example of how we could solve the issue:

Too long for our pill shape.


We will add a popup on hover that will show all info, just like with the price tag or the other tags.
