### ISSUE TITLE
Seite Funktioniert nicht ohne Javascript

### ISSUE THREAD

**Issue by phikal** [mensatt/frontend-old#183]
Ich war vor kurzem verwritt weshalb die Seite keine Informationen hatte.  Es stellt sich heraus, dass weil ich Javascript deaktiviere erscheint die Seite in einem "Lade-Zustand" ohne ein Hinweis darauf, dass Javascript aktiviert sein muss.

Es wäre entweder gut ein statischen Fallback oder zumindest eine Warnung anzugeben.

**Comment by GamerBene19** [comment]
Hmm, ja ich sehe das Problem. Das Frontend ist in NextJS geschrieben - wie der Name vermuten lässt braucht es Javascript um zu funktionieren. Auf Anhieb fällt mir keine gute/einfache Möglichkeit ein eine solche Nachricht einzubauen und auch eine kurze Google-Suche war nicht erfolgreich. Ich glaube aber schon, das ein disclaimer wichtig ist, deswegen ist das definitiv etwas, dass man im Hinterkopf behalten sollte.

Vielen Dank für das Issue :+1:

**Comment by phikal** [comment]
> Auf Anhieb fällt mir keine gute/einfache Möglichkeit ein eine solche Nachricht einzubauen

Wieso würde ein [`<noscript>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) Tag nicht funktionieren?

**Comment by GamerBene19** [comment]
> > Auf Anhieb fällt mir keine gute/einfache Möglichkeit ein eine solche Nachricht einzubauen
> 
> Wieso würde ein [`<noscript>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) Tag nicht funktionieren?

Tut es, ist mir kurz nach Abschicken aufgefallen. Wird durch #184 hinzugefügt.
