### ISSUE TITLE
Feature Request: Increase site accessibility

### ISSUE THREAD

**Issue by stormofice** [mensatt/frontend-old#25]
The site currently is not optimized for accessibility.

Features to add:

- [x] #41
- [x] #39

**Comment by GamerBene19** [comment]
@stormofice regarding 
> Focus on clickable elements is not currently shown (day selector)

Could you please elaborate what you mean by that? The navigation icons *do* turn gray on hover for me.

**Comment by stormofice** [comment]
If you press tab (repeatedly), the days do not get focused.

**Comment by GamerBene19** [comment]
Split up into two issues. See their progress there.

**Comment by GamerBene19** [comment]
This issue should be closed once #58 is merged.
