### ISSUE TITLE
The selected date should be part of the url

### ISSUE THREAD

**Issue by tobiges** [mensatt/frontend-old#47]
The selected date should be part of the url, otherwise the date will always be reset to the current date on reload.  
It would also be way easier to share links of the selected date.

**Comment by GamerBene19** [comment]
Blocked until #59 is merged. Does not make sense to build a solution relying on redux, when apollo client is right around the corner.

**Comment by tobiges** [comment]
the selected date should be part of the url instead of the weekday

https://mensatt.de/en?weekday=2
->
https://mensatt.de/en?date=2022-06-08
