### ISSUE TITLE
Pointer cursor on api switch button

### ISSUE THREAD

**Issue by stormofice** [mensatt/frontend-old#50]
It would be nice if we could use a pointer cursor ([see pointer cursor here](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#syntax)), as it is normally used for clickable elements (such as buttons).
![grafik](https://user-images.githubusercontent.com/58337328/171970992-8ae7d720-ff1f-466a-adf1-893ceccbf5e2.png)

**Comment by maanex** [comment]
Fixed in https://github.com/mensatt/frontend/pull/58
