### ISSUE TITLE
Time-Handling seems off

### ISSUE THREAD

**Issue by GamerBene19** [mensatt/frontend-old#57]
When I request occurrences on Monday morning MEST (e.g. 2022-05-03 at 00:13) which is `2022-05-22T22:13:55.561Z` in UTC I would expect to get results but I don't.

**Comment by stormofice** [comment]
@StealWonders @tobiges Bump!

**Comment by stormofice** [comment]
@GamerBene19 Bump!

**Comment by GamerBene19** [comment]
This issue was originally a backend issue. Since opening the api has changed and now accepts only dates (in the format `YYYY-MM-DD`. The frontend now has to make sure to request the right date from the API. The old problem occured between 0:00 and 2:00 MEST

**Comment by GamerBene19** [comment]
I just tried to replicate the issue by changing my PC-time to 00:00 MEST (also tried 01:00). Could not replicate the issue (anymore). This needs to be tried out between 0:00 and 2:00 in the morning with https://mensatt.de. If the issue does not occur anymore this issue can be closed.

Perhaps @stormofice or @tobiges could try this out after midnight?

**Comment by stormofice** [comment]
Issue should be fixed, all occurrences seem to be on time.
