### ISSUE TITLE
Add support for multiple locations

### ISSUE THREAD

**Issue by tobiges** [mensatt/frontend-old#74]
The Graphql api serves the occurrence info for many different locations.
In the frontend the difference between the Süd and Devmensa is that they target different endpoints. This is not the case with for the locations in graphql.

Transition away from the current approach to the way it is handled in graphql.
It would be possible that the netlify preview build target the dev-api and the main site targets the production api.

**Comment by GamerBene19** [comment]
Currently the functionality of the api-switcher (switching to the dev-endpoint) won't be replaced by supporting multiple locations in a query. 
This task can be started/done once the prod API actually _works_ (and - ideally - has data in it). We should then look into a setup that works like this:
https://mensatt.de => Südmensa/Langemarkplatz/other locations via the prod api (only)
https://dev.mensatt.de => Same as prod plus possibility to switch to dev-api (and its various locations)

**Comment by GamerBene19** [comment]
This was already implemented in #126 
![image](https://user-images.githubusercontent.com/20821976/196293638-1f746c9b-2794-4921-81c8-8cbef11cea90.png)
